package constants

const val QUANTITY_DEFAULT_VALUE_ANSWER_COUNT = 0
const val QUANTITY_WORDS_FOR_LEARNING = 4
const val QUANTITY_MINIMAL_CORRECT_ANSWER = 3

const val MINIMUM_QUANTITY_SHOWING_UNLEARNED_WORDS = 1
const val MAXIMUM_QUANTITY_SHOWING_UNLEARNED_WORDS = 10
